# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atm(object):
    def setupUi(self, atm):
        atm.setObjectName("atm")
        atm.resize(500, 400)
        atm.setStyleSheet("#atm{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.deposit_btn = QtWidgets.QPushButton(atm)
        self.deposit_btn.setGeometry(QtCore.QRect(390, 210, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deposit_btn.setFont(font)
        self.deposit_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.deposit_btn.setObjectName("deposit_btn")
        self.cash_btn = QtWidgets.QPushButton(atm)
        self.cash_btn.setGeometry(QtCore.QRect(390, 110, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cash_btn.setFont(font)
        self.cash_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.cash_btn.setObjectName("cash_btn")
        self.label1 = QtWidgets.QLabel(atm)
        self.label1.setGeometry(QtCore.QRect(120, 70, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 0, 0)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.card_out_btn = QtWidgets.QPushButton(atm)
        self.card_out_btn.setGeometry(QtCore.QRect(200, 350, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.card_out_btn.setFont(font)
        self.card_out_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(255, 0, 0);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.card_out_btn.setObjectName("card_out_btn")
        self.transfer_btn = QtWidgets.QPushButton(atm)
        self.transfer_btn.setGeometry(QtCore.QRect(0, 110, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.transfer_btn.setFont(font)
        self.transfer_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.transfer_btn.setObjectName("transfer_btn")
        self.inquiry_btn = QtWidgets.QPushButton(atm)
        self.inquiry_btn.setGeometry(QtCore.QRect(0, 210, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inquiry_btn.setFont(font)
        self.inquiry_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.inquiry_btn.setObjectName("inquiry_btn")
        self.pwchange_btn = QtWidgets.QPushButton(atm)
        self.pwchange_btn.setGeometry(QtCore.QRect(390, 320, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pwchange_btn.setFont(font)
        self.pwchange_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.pwchange_btn.setObjectName("pwchange_btn")
        self.record_btn = QtWidgets.QPushButton(atm)
        self.record_btn.setGeometry(QtCore.QRect(0, 320, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.record_btn.setFont(font)
        self.record_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.record_btn.setObjectName("record_btn")
        self.listView = QtWidgets.QListView(atm)
        self.listView.setGeometry(QtCore.QRect(-10, -9, 511, 421))
        self.listView.setStyleSheet("border-image:url(:/back/back.png)")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.deposit_btn.raise_()
        self.cash_btn.raise_()
        self.label1.raise_()
        self.card_out_btn.raise_()
        self.transfer_btn.raise_()
        self.inquiry_btn.raise_()
        self.pwchange_btn.raise_()
        self.record_btn.raise_()

        self.retranslateUi(atm)
        QtCore.QMetaObject.connectSlotsByName(atm)

    def retranslateUi(self, atm):
        _translate = QtCore.QCoreApplication.translate
        atm.setWindowTitle(_translate("atm", "ATM"))
        self.deposit_btn.setText(_translate("atm", "存款"))
        self.cash_btn.setText(_translate("atm", "取款"))
        self.label1.setText(_translate("atm", "您好，请选择所需服务！"))
        self.card_out_btn.setText(_translate("atm", "退卡 Exit"))
        self.transfer_btn.setText(_translate("atm", "转账"))
        self.inquiry_btn.setText(_translate("atm", "查询"))
        self.pwchange_btn.setText(_translate("atm", "修改密码"))
        self.record_btn.setText(_translate("atm", "交易记录"))
import hnu_rc
