# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cashAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cashAccount(object):
    def setupUi(self, cashAccount):
        cashAccount.setObjectName("cashAccount")
        cashAccount.resize(500, 400)
        cashAccount.setStyleSheet("#atm{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.credit_btn = QtWidgets.QPushButton(cashAccount)
        self.credit_btn.setGeometry(QtCore.QRect(380, 150, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.credit_btn.setFont(font)
        self.credit_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.credit_btn.setObjectName("credit_btn")
        self.settime_btn = QtWidgets.QPushButton(cashAccount)
        self.settime_btn.setGeometry(QtCore.QRect(200, 150, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.settime_btn.setFont(font)
        self.settime_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.settime_btn.setObjectName("settime_btn")
        self.label1 = QtWidgets.QLabel(cashAccount)
        self.label1.setGeometry(QtCore.QRect(10, 240, 471, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 0, 0)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.livetime_btn = QtWidgets.QPushButton(cashAccount)
        self.livetime_btn.setGeometry(QtCore.QRect(10, 150, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.livetime_btn.setFont(font)
        self.livetime_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.livetime_btn.setObjectName("livetime_btn")
        self.label1_2 = QtWidgets.QLabel(cashAccount)
        self.label1_2.setGeometry(QtCore.QRect(80, 60, 341, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1_2.setFont(font)
        self.label1_2.setStyleSheet("color:rgb(255, 0, 0)")
        self.label1_2.setScaledContents(False)
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setWordWrap(False)
        self.label1_2.setOpenExternalLinks(False)
        self.label1_2.setObjectName("label1_2")
        self.listView = QtWidgets.QListView(cashAccount)
        self.listView.setGeometry(QtCore.QRect(0, 0, 501, 401))
        self.listView.setStyleSheet("border-image:url(:/back/back.png)")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.credit_btn.raise_()
        self.settime_btn.raise_()
        self.label1.raise_()
        self.livetime_btn.raise_()
        self.label1_2.raise_()

        self.retranslateUi(cashAccount)
        QtCore.QMetaObject.connectSlotsByName(cashAccount)

    def retranslateUi(self, cashAccount):
        _translate = QtCore.QCoreApplication.translate
        cashAccount.setWindowTitle(_translate("cashAccount", "cashAccount"))
        self.credit_btn.setText(_translate("cashAccount", "信用卡"))
        self.settime_btn.setText(_translate("cashAccount", "定期账户"))
        self.label1.setText(_translate("cashAccount", "注意：每个账户每天可最多取出两千元"))
        self.livetime_btn.setText(_translate("cashAccount", "活期账户"))
        self.label1_2.setText(_translate("cashAccount", "请选择账户"))
import hnu_rc
