# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deposit1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deposit1(object):
    def setupUi(self, deposit1):
        deposit1.setObjectName("deposit1")
        deposit1.resize(500, 400)
        deposit1.setStyleSheet("#deposit1{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.return_btn = QtWidgets.QPushButton(deposit1)
        self.return_btn.setGeometry(QtCore.QRect(360, 300, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.return_btn.setFont(font)
        self.return_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.return_btn.setObjectName("return_btn")
        self.amount = QtWidgets.QLineEdit(deposit1)
        self.amount.setGeometry(QtCore.QRect(170, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.amount.setFont(font)
        self.amount.setStyleSheet("")
        self.amount.setObjectName("amount")
        self.label1_3 = QtWidgets.QLabel(deposit1)
        self.label1_3.setGeometry(QtCore.QRect(100, 230, 341, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_3.sizePolicy().hasHeightForWidth())
        self.label1_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1_3.setFont(font)
        self.label1_3.setStyleSheet("color:rgb(255, 0, 0)")
        self.label1_3.setScaledContents(False)
        self.label1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_3.setWordWrap(False)
        self.label1_3.setOpenExternalLinks(False)
        self.label1_3.setObjectName("label1_3")
        self.card_out_btn = QtWidgets.QPushButton(deposit1)
        self.card_out_btn.setGeometry(QtCore.QRect(30, 300, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.card_out_btn.setFont(font)
        self.card_out_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(255, 0, 0);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.card_out_btn.setObjectName("card_out_btn")
        self.label1 = QtWidgets.QLabel(deposit1)
        self.label1.setGeometry(QtCore.QRect(120, 80, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 0, 0)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.deposit_btn = QtWidgets.QPushButton(deposit1)
        self.deposit_btn.setGeometry(QtCore.QRect(360, 160, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deposit_btn.setFont(font)
        self.deposit_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.deposit_btn.setObjectName("deposit_btn")
        self.listView = QtWidgets.QListView(deposit1)
        self.listView.setGeometry(QtCore.QRect(0, 0, 501, 401))
        self.listView.setStyleSheet("border-image:url(:/back/back.png)")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.return_btn.raise_()
        self.amount.raise_()
        self.label1_3.raise_()
        self.card_out_btn.raise_()
        self.label1.raise_()
        self.deposit_btn.raise_()

        self.retranslateUi(deposit1)
        QtCore.QMetaObject.connectSlotsByName(deposit1)

    def retranslateUi(self, deposit1):
        _translate = QtCore.QCoreApplication.translate
        deposit1.setWindowTitle(_translate("deposit1", "deposit1"))
        self.return_btn.setText(_translate("deposit1", "返回"))
        self.label1_3.setText(_translate("deposit1", "注意：金额必须为100整数倍！"))
        self.card_out_btn.setText(_translate("deposit1", "退卡"))
        self.label1.setText(_translate("deposit1", "请输入存款金额！"))
        self.deposit_btn.setText(_translate("deposit1", "存款"))
import hnu_rc
