# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cash.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cash(object):
    def setupUi(self, cash):
        cash.setObjectName("cash")
        cash.resize(500, 400)
        cash.setStyleSheet("#cash{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.btn100 = QtWidgets.QPushButton(cash)
        self.btn100.setGeometry(QtCore.QRect(0, 130, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn100.setFont(font)
        self.btn100.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn100.setObjectName("btn100")
        self.btn500 = QtWidgets.QPushButton(cash)
        self.btn500.setGeometry(QtCore.QRect(0, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn500.setFont(font)
        self.btn500.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn500.setObjectName("btn500")
        self.label1 = QtWidgets.QLabel(cash)
        self.label1.setGeometry(QtCore.QRect(130, 60, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255,0, 0)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.card_out_btn = QtWidgets.QPushButton(cash)
        self.card_out_btn.setGeometry(QtCore.QRect(-10, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.card_out_btn.setFont(font)
        self.card_out_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(255, 0, 0);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.card_out_btn.setObjectName("card_out_btn")
        self.btn1000 = QtWidgets.QPushButton(cash)
        self.btn1000.setGeometry(QtCore.QRect(390, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn1000.setFont(font)
        self.btn1000.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn1000.setObjectName("btn1000")
        self.other_amount_btn = QtWidgets.QPushButton(cash)
        self.other_amount_btn.setGeometry(QtCore.QRect(390, 240, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.other_amount_btn.setFont(font)
        self.other_amount_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.other_amount_btn.setObjectName("other_amount_btn")
        self.btn2000 = QtWidgets.QPushButton(cash)
        self.btn2000.setGeometry(QtCore.QRect(390, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn2000.setFont(font)
        self.btn2000.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn2000.setObjectName("btn2000")
        self.return_btn = QtWidgets.QPushButton(cash)
        self.return_btn.setGeometry(QtCore.QRect(390, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.return_btn.setFont(font)
        self.return_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(14, 122, 255);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.return_btn.setObjectName("return_btn")
        self.listView = QtWidgets.QListView(cash)
        self.listView.setGeometry(QtCore.QRect(-10, 0, 511, 401))
        self.listView.setStyleSheet("border-image:url(:/back/back.png)")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.btn100.raise_()
        self.btn500.raise_()
        self.label1.raise_()
        self.card_out_btn.raise_()
        self.btn1000.raise_()
        self.other_amount_btn.raise_()
        self.btn2000.raise_()
        self.return_btn.raise_()

        self.retranslateUi(cash)
        QtCore.QMetaObject.connectSlotsByName(cash)

    def retranslateUi(self, cash):
        _translate = QtCore.QCoreApplication.translate
        cash.setWindowTitle(_translate("cash", "cash"))
        self.btn100.setText(_translate("cash", "100"))
        self.btn500.setText(_translate("cash", "500"))
        self.label1.setText(_translate("cash", "请选择取款金额！"))
        self.card_out_btn.setText(_translate("cash", "<- 退 卡"))
        self.btn1000.setText(_translate("cash", "1000"))
        self.other_amount_btn.setText(_translate("cash", "其他金额"))
        self.btn2000.setText(_translate("cash", "2000"))
        self.return_btn.setText(_translate("cash", "返 回 ->"))
